name: reprobench
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda-client
  - ansimarkup
  - ansiwrap=0.8.4
  - apsw=3.25.2.r1
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - backcall=0.1.0
  - backports=1.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bcrypt=3.1.6
  - beautifulsoup4=4.7.1
  - better_exceptions_fork=0.2.1.post6
  - bleach=3.1.0
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cffi=1.12.3
  - chardet=3.0.4
  - click=7.0
  - clyent=1.2.2
  - colorama=0.4.1
  - conda=4.6.14
  - conda-package-handling=1.1.5
  - conda-verify=3.1.1
  - cryptography=2.6.1
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.5.0
  - entrypoints=0.3
  - filelock=3.0.10
  - freetype=2.10.0
  - future=0.17.1
  - gettext=0.19.8.1
  - gevent=1.4.0
  - glib=2.58.3
  - glob2=0.6
  - greenlet=0.4.15
  - icu=58.2
  - idna=2.8
  - ipykernel=5.1.1
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - kiwisolver=1.1.0
  - leveldb
  - libarchive=3.3.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx
  - libffi=3.2.1
  - libiconv=1.15
  - liblapack=3.8.0
  - liblief=0.9.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libxml2=2.9.9
  - loguru=0.2.5
  - lz4-c=1.8.3
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib-base=3.1.0
  - mistune=0.8.4
  - msgpack-python=0.6.1
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - notebook=5.7.8
  - numpy=1.16.3
  - openblas=0.3.6
  - openssl=1.1.1b
  - pandas=0.24.2
  - pandoc=2.7.2
  - pandocfilters=1.4.2
  - papermill=1.0.0
  - paramiko=2.5.0
  - parso=0.4.0
  - pathspec=0.5.9
  - patsy=0.5.1
  - pcre=8.43
  - peewee=3.9.2
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.1
  - pkginfo=1.5.0.1
  - prometheus_client=0.7.0
  - prompt_toolkit=2.0.9
  - psutil=5.6.2
  - ptyprocess=0.6.0
  - py-cpuinfo=5.0.0
  - py-lief=0.9.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pygments=2.4.0
  - pynacl=1.3.0
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyqt>=5.9.2
  - pyrsistent=0.15.2
  - pysocks=1.7.0
  - python>=3.7.3
  - python-dateutil=2.8.0
  - python-leveldb
  - python-libarchive-c=2.8
  - pytz=2019.1
  - pyyaml=5.1
  - pyzmq=18.0.1
  - qt=5.9.7
  - qtconsole=4.5.1
  - requests=2.22.0
  - retrying=1.3.3
  - ruamel=1.0
  - ruamel.yaml=0.15.96
  - ruamel_yaml=0.15.71
  - scipy=1.3.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - snappy=1.1.7
  - soupsieve=1.9.1
  - sqlite>=3.26.0
  - sshtunnel=0.1.4
  - statsmodels=0.9.0
  - strictyaml=1.0.1
  - tenacity=5.0.4
  - terminado=0.8.2
  - testpath=0.4.2
  - textwrap3=0.9.2
  - tk=8.6.9
  - tornado=6.0.2
  - tqdm=4.32.1
  - traitlets=4.3.2
  - urllib3=1.24.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - widgetsnbextension=3.4.2
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.3
  - pip:
      - configspace==0.4.10
      - cython==0.29.7
      - psmon==1.1.1
      - typing==3.6.6
      - appnope==0.1.0
      - libgfortran==3.0.1

