#config: "./benchmark_thp_sat.yml"
config: "./benchmark_thp_asp.yml"
#config: "./benchmark_thp_bmc_sw.yml"
#config: "./benchmark_thp_bmc_hw.yml"
#config: "./benchmark_thp_maxsat.yml"
output: "output"
server_url: "tcp://127.0.0.1:31313"
